{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "phrase-loop-player-front.serviceAccountName" . }}
  labels:
{{ include "phrase-loop-player-front.labels" . | nindent 4 }}
{{- end -}}
